### ISSUE TITLE
Create a schedule for the project

### ISSUE THREAD

**Issue by povidllo** [povidllo/Calculation-module-based-on-PINN-neural-network-architecture#3]

**Comment by YogNare** [comment]
https://docs.google.com/document/d/1wQqiUWpEEoEhX7aFsbdNrugjQ7PpLeeEZgsu9C87qV0/edit?usp=sharing

**Comment by povidllo** [comment]
[Our project schedule.pdf](https://github.com/user-attachments/files/17376851/Our.project.schedule.pdf)
